# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard.proto',
  package='standard',
  syntax='proto3',
  serialized_pb=_b('\n\x0estandard.proto\x12\x08standard\"=\n\x0fStandardRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x0e\n\x06method\x18\x03 \x01(\t\"<\n\rStandardReply\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\x88\x02\n\x08Standard\x12>\n\x06\x43reate\x12\x19.standard.StandardRequest\x1a\x17.standard.StandardReply\"\x00\x12<\n\x04Read\x12\x19.standard.StandardRequest\x1a\x17.standard.StandardReply\"\x00\x12>\n\x06Update\x12\x19.standard.StandardRequest\x1a\x17.standard.StandardReply\"\x00\x12>\n\x06\x44\x65lete\x12\x19.standard.StandardRequest\x1a\x17.standard.StandardReply\"\x00\x42\x17\x42\rStandardProtoP\x01\xa2\x02\x03STDb\x06proto3')
)




_STANDARDREQUEST = _descriptor.Descriptor(
  name='StandardRequest',
  full_name='standard.StandardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='standard.StandardRequest.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='standard.StandardRequest.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='standard.StandardRequest.method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=89,
)


_STANDARDREPLY = _descriptor.Descriptor(
  name='StandardReply',
  full_name='standard.StandardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='standard.StandardReply.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='standard.StandardReply.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='standard.StandardReply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['StandardRequest'] = _STANDARDREQUEST
DESCRIPTOR.message_types_by_name['StandardReply'] = _STANDARDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StandardRequest = _reflection.GeneratedProtocolMessageType('StandardRequest', (_message.Message,), dict(
  DESCRIPTOR = _STANDARDREQUEST,
  __module__ = 'standard_pb2'
  # @@protoc_insertion_point(class_scope:standard.StandardRequest)
  ))
_sym_db.RegisterMessage(StandardRequest)

StandardReply = _reflection.GeneratedProtocolMessageType('StandardReply', (_message.Message,), dict(
  DESCRIPTOR = _STANDARDREPLY,
  __module__ = 'standard_pb2'
  # @@protoc_insertion_point(class_scope:standard.StandardReply)
  ))
_sym_db.RegisterMessage(StandardReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\rStandardProtoP\001\242\002\003STD'))

_STANDARD = _descriptor.ServiceDescriptor(
  name='Standard',
  full_name='standard.Standard',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=154,
  serialized_end=418,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='standard.Standard.Create',
    index=0,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='standard.Standard.Read',
    index=1,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='standard.Standard.Update',
    index=2,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='standard.Standard.Delete',
    index=3,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STANDARD)

DESCRIPTOR.services_by_name['Standard'] = _STANDARD

# @@protoc_insertion_point(module_scope)
